### ISSUE TITLE
Support for Newer Python Versions: 3.12 and 3.13

### ISSUE THREAD

**Issue by pgarrett-scripps** [theGreatHerrLebert/sagepy#11]
Would it be possible to support more versions of python in the PyPI releases? I'm trying to install sagepy into an environment running Python 3.12, but the last compatible version of sagepy-connector is 0.2.2.

Seems like you might be able to just add more python versions to: .github/workflows/sagepy-connector-publish.yml

**Comment by theGreatHerrLebert** [comment]
Hello there,

Sure thing. After some tests, I found that Python 3.13 is not yet supported by the GitHub runners. However, Python 3.12 is supported.

I ran tests on Linux, and everything worked as expected with Python 3.12. If you could confirm that the installation from PyPI works correctly on your end, we could add support for Python 3.13 once it is officially released later this year.

Best regards,
David

**Comment by pgarrett-scripps** [comment]
Hi David,

Thanks for the quick fix! The PyPI install is now working for me on Python 3.12.

Regarding support for Python 3.13, I mistakenly thought it was already released, so waiting for the official release sounds like a good plan.

I'm also happy to contribute to the project. I have a fork with added type annotations and some additional features, and I can submit a pull request if you're interested. Feel free to reach out to me at pgarrett@scripps.edu.

Best,
Patrick

**Comment by theGreatHerrLebert** [comment]
Hi Patrick,

Thanks for your interest in contributing, that is of course most welcome! The project is still in its early stages, so many features are still in progress. Please feel free to open pull requests or start discussions on what you’d like to see added or improved.

I’ll also be working on adding more documentation soon to make it easier for everyone to use the tool without having to dive into the code directly.

Best regards,
David
